/**
 * Copyright (C), 2024-08-10
 * @author LinXun
 * @date 2024/8/10 11:14
 * @version 1.0
 * @description: 项目中的常量
 */

export default class CommonConstants {
  /**
   * 安全区常量名
   */
  static readonly AVOID_HEIGHT_TOP: string = "topAvoidHeight";
  static readonly AVOID_HEIGHT_BOTTOM: string = "bottomAvoidHeight";
  /**
   * 日志TAG
   */
  // APP日志TAG
  static readonly LOGGER_PREFIX: string = "Framework";
}